export const addNewLotInputsInfo = (farms, shadingFarmStates) => {
  const inputs = [
    {
      name: "farm",
      element: "dropDown",
      placeholder: "Finca",
      isRequired: true,
      label: "Seleccione la finca del lote",
      items: farms,
      key: 1,
      id: 1,
    },
    {
      name: "lotName",
      element: "input",
      placeholder: "Nombre del lote",
      isRequired: true,
      label: "Ingrese el nombre del documento",
      type: "default",
      isPassword: false,
      key: 2,
      id: 2,
    },
    {
      name: "sowingYear",
      element: "input",
      placeholder: "Año de siembra",
      isRequired: false,
      label: "Ingrese el año de siembra",
      type: "numeric",
      isPassword: false,
      key: 3,
      id: 3,
    },
    {
      name: "zocaYear",
      element: "input",
      placeholder: "Año de zoca",
      isRequired: false,
      label: "Ingrese el año de zoca",
      type: "numeric",
      isPassword: false,
      key: 4,
      id: 4,
    },
    {
      name: "hectares",
      element: "input",
      placeholder: "Hectareas del lote",
      isRequired: true,
      label: "Ingrese el numero de hectareas",
      type: "numeric",
      isPassword: false,
      key: 5,
      id: 5,
    },
    {
      name: "numberPlants",
      element: "input",
      placeholder: "Número de plantas",
      isRequired: false,
      label: "Ingrese el numero de plantas",
      type: "numeric",
      isPassword: false,
      key: 6,
      id: 6,
    },
    {
      name: "shadingFarmState",
      element: "dropDown",
      placeholder: "¿El lote es sombrio?",
      isRequired: true,
      label: "¿El lote es sombrio?",
      items: shadingFarmStates,
      key: 7,
      id: 7,
    },
    {
      name: "note",
      element: "input",
      placeholder: "Nota",
      isRequired: false,
      label: "Ingrese una nota",
      type: "default",
      isPassword: false,
      multiline: true,
      numberOfLines: 5,
      key: 8,
      id: 8,
    },
  ];

  return inputs;
};
