export const updateWageInputsInfo = (
  lots,
  workers,
  activities,
  contractTypes,
  wage
) => {
  const inputs = [
    {
      name: "date",
      element: "datePicker",
      placeholder: "Fecha del jornal",
      isRequired: true,
      label: "Ingrese la fecha del jornal",
      value: Date.parse(wage.date.toDate()),
      key: 1,
      id: 1,
    },
    {
      name: "lot",
      element: "dropDown",
      placeholder: "Lote",
      isRequired: true,
      label: "Seleccione el lote",
      items: lots,
      value: wage.lot,
      key: 2,
      id: 2,
    },
    {
      name: "worker",
      element: "dropDown",
      placeholder: "Trabajador",
      isRequired: true,
      label: "Seleccione el trabajador",
      items: workers,
      value: wage.worker,
      key: 3,
      id: 3,
    },
    {
      name: "activity",
      element: "dropDown",
      placeholder: "Actividad",
      isRequired: true,
      label: "Seleccione la actividad",
      items: activities,
      value: wage.activity,
      key: 4,
      id: 4,
    },
    {
      name: "contractType",
      element: "dropDown",
      placeholder: "Tipo de contrato",
      isRequired: true,
      label: "Seleccione el tipo de contrato",
      items: contractTypes,
      value: wage.contractType,
      key: 5,
      id: 5,
    },
    {
      name: "kgCollected",
      element: "input",
      placeholder: "Cantidad recolectada (kg)",
      isRequired: true,
      label: "Ingrese la cantidad recolectada (kg)",
      type: "numeric",
      isPassword: false,
      value: wage.kgCollected,
      key: 6,
      id: 6,
    },
    {
      name: "priceByKg",
      element: "input",
      placeholder: "Precio por kg",
      isRequired: true,
      label: "Ingrese el precio por kg",
      type: "numeric",
      isPassword: false,
      value: wage.priceByKg,
      key: 6,
      id: 6,
    },
    {
      name: "note",
      element: "input",
      placeholder: "Nota",
      isRequired: false,
      label: "Ingrese una nota",
      type: "default",
      isPassword: false,
      multiline: true,
      numberOfLines: 5,
      value: wage.note,
      key: 7,
      id: 7,
    },
  ];

  return inputs;
};
