export const updateCollectionInputsInfo = (lots, workers, collection) => {
  const inputs = [
    {
      name: "date",
      element: "datePicker",
      placeholder: "Fecha de recolección",
      isRequired: true,
      label: "Ingrese la fecha de recolección",
      value: Date.parse(collection.date.toDate()),
      key: 1,
      id: 1,
    },
    {
      name: "lot",
      element: "dropDown",
      placeholder: "Lote",
      isRequired: true,
      label: "Seleccione el lote",
      items: lots,
      value: collection.lot,
      key: 2,
      id: 2,
    },
    {
      name: "worker",
      element: "dropDown",
      placeholder: "Trabajador",
      isRequired: true,
      label: "Seleccione el trabajador",
      items: workers,
      value: collection.worker,
      key: 3,
      id: 3,
    },
    {
      name: "kgCollected",
      element: "input",
      placeholder: "Cantidad recolectada (kg)",
      isRequired: false,
      label: "Ingrese la cantidad (kg)",
      type: "numeric",
      value: collection.kgCollected,
      isPassword: false,
      key: 4,
      id: 4,
    },
    {
      name: "priceByKg",
      element: "input",
      placeholder: "Precio por kg",
      isRequired: false,
      label: "Ingrese el precio por kg",
      type: "numeric",
      value: collection.priceByKg,
      isPassword: false,
      key: 5,
      id: 5,
    },
    {
      name: "note",
      element: "input",
      placeholder: "Nota",
      isRequired: false,
      label: "Ingrese una nota",
      type: "default",
      isPassword: false,
      multiline: true,
      numberOfLines: 5,
      value: collection.note,
      key: 6,
      id: 6,
    },
  ];

  return inputs;
};
